image: node:20

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm ci
    - npx @11ty/eleventy --output=test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - npm ci
    - npx @11ty/eleventy --output=public
  artifacts:
    paths:
      - public
  only:
    - master
