# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carlos Asmat
linkedin: http://linkedin.com/in/casmat
github: http://github.com/Sotilrac
youtube: https://youtube.com/c/CarlosAsmat
phone: '{"iv":"bvxHNGo4Ibwx16IfdY7cCQ==","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"sKFccCvjqYU=","ct":"SOsRUJJzNoTOsu7uG+phkqqY5KXijw=="}'
email: '{"iv":"205IpwCXbNCmLrWfJ/W4cQ==","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"sKFccCvjqYU=","ct":"tAwrTZLNnGqHQb/mu1ygs3YjITxX"}'
description: > # this means to ignore newlines until "baseurl:"
  Carlos' Resume, portfolio and blog. My projects span software,
  electronics and robotics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asmat.ca" # the base hostname & protocol for your site
twitter_username: asmat
github_username:  sotilrac

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - vendor
  - README.md

exclude_from_watch:
  - node_modules
  - package.json
  - vendor
  - README.md

include:
  - "img"